import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google"
import Header from "./_components/Header";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--Roboto'
})



export const metadata: Metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/icon.png" sizes=""/>
      <body className={`${roboto.className} antialiased bg-primary-850 text-primary-100 min-h-screen flex flex-col relative`}>
        <Header/>
        <div className="">
          <main className="flex justify-between items-center w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
